apiVersion: batch/v1
kind: Job

metadata:
  name: easyshop-migration
  namespace: easyshop-ns

spec:
  template:
    spec:
      containers:
      - name: migration
        image: learnersubha/easyshop-app-migration:latest
        imagePullPolicy: Always
        env:
        - name: MONGODB_URI
          value: "mongodb://mongodb-service:27017/easyshop"
      restartPolicy: OnFailure
