apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
  namespace: easyshop-ns
data:
  MONGODB_URI: "mongodb://mongodb-service:27017/easyshop"
  NODE_ENV: "production"
  NEXT_PUBLIC_API_URL: "http://34.242.255.167/api"  # Replace with your YOUR_EC2_PUBLIC_IP
  NEXTAUTH_URL: "http://34.242.255.167"             # Replace with your YOUR_EC2_PUBLIC_IP
  NEXTAUTH_SECRET: "8ebd611ed5b60bde887fbc88814e4274141a767d8cc527fa296ebc840247c330"  ## Create your Own NEXTAUTH_SECRET secret
  JWT_SECRET: "wZQ9gUk5vNcVTqrVhuoqe54Y3eifR22HWEU46cfIem0="   ## Create your Own JWT_SECRET secret
